version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/FunctionApp"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    commit-message:
      prefix: "NuGet"
