-- This table will be recreated if staging fields change detected in functionApp
CREATE TABLE [his].[matches](
    [bk_matches]                NVARCHAR(100)   NOT NULL,
    -- Shared fields (/programma + /uitslagen)
    [wedstrijddatum]            NVARCHAR(50)    NULL,
    [wedstrijdcode]             BIGINT          NULL,
    [wedstrijdnummer]           BIGINT          NULL,
    [datum]                     NVARCHAR(50)    NULL,
    [wedstrijd]                 NVARCHAR(200)   NULL,
    [accommodatie]              NVARCHAR(200)   NULL,
    [aanvangstijd]              NVARCHAR(50)    NULL,
    [thuisteam]                 NVARCHAR(100)   NULL,
    [thuisteamid]               NVARCHAR(50)    NULL,
    [thuisteamlogo]             NVARCHAR(1000)  NULL,
    [thuisteamclubrelatiecode]  NVARCHAR(50)    NULL,
    [uitteamclubrelatiecode]    NVARCHAR(50)    NULL,
    [uitteam]                   NVARCHAR(100)   NULL,
    [uitteamid]                 NVARCHAR(50)    NULL,
    [uitteamlogo]               NVARCHAR(1000)  NULL,
    [competitiesoort]           NVARCHAR(200)   NULL,
    [status]                    NVARCHAR(50)    NULL,
    [meer]                      NVARCHAR(1000)  NULL,
    -- /programma specific fields
    [teamnaam]                  NVARCHAR(100)   NULL,
    [teamvolgorde]              INT             NULL,
    [competitie]                NVARCHAR(200)   NULL,
    [klasse]                    NVARCHAR(100)   NULL,
    [poule]                     NVARCHAR(100)   NULL,
    [klassepoule]               NVARCHAR(200)   NULL,
    [kaledatum]                 NVARCHAR(50)    NULL,
    [vertrektijd]               NVARCHAR(50)    NULL,
    [verzameltijd]              NVARCHAR(50)    NULL,
    [scheidsrechters]           NVARCHAR(500)   NULL,
    [scheidsrechter]            NVARCHAR(200)   NULL,
    [veld]                      NVARCHAR(100)   NULL,
    [locatie]                   NVARCHAR(100)   NULL,
    [plaats]                    NVARCHAR(100)   NULL,
    [rijders]                   NVARCHAR(200)   NULL,
    [kleedkamerthuisteam]       NVARCHAR(50)    NULL,
    [kleedkameruitteam]         NVARCHAR(50)    NULL,
    [kleedkamerscheidsrechter]  NVARCHAR(50)    NULL,
    -- /uitslagen specific fields (scores + admin fields)
    [datumopgemaakt]            NVARCHAR(50)    NULL,
    [uitslag]                   NVARCHAR(50)    NULL,
    [uitslag-regulier]          NVARCHAR(50)    NULL,
    [uitslag-nv]                NVARCHAR(50)    NULL,
    [uitslag-s]                 NVARCHAR(50)    NULL,
    [competitienaam]            NVARCHAR(200)   NULL,
    [eigenteam]                 NVARCHAR(50)    NULL,
    [sportomschrijving]         NVARCHAR(100)   NULL,
    [verenigingswedstrijd]      NVARCHAR(50)    NULL,
    -- Metadata
    [mta_inserted]              DATETIME        NULL,
    [mta_modified]              DATETIME        NULL,
    [mta_deleted]               DATETIME        NULL
)
